name: Update develop after master merge

on:
  push:
    branches:
    - master


jobs:
  develop_update:
    runs-on: ubuntu-latest

    if: github.repository == 'qmk/qmk_firmware'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update develop from master
      shell: 'bash {0}'
      run: |
        git fetch origin master develop
        git checkout develop

        if [ -e .locked ]; then
            echo 'Develop branch is locked, aborting update!'
            exit 1
        fi

        git merge origin/master
        git push origin develop
