name: Update develop after master merge

on:
  push:
    branches:
    - master


jobs:
  develop_update:
    runs-on: ubuntu-latest

    if: github.repository == 'qmk/qmk_firmware'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update develop from master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: 'bash {0}'
      run: |
        if [ -e .locked ]; then
            echo 'Develop branch is locked, aborting update!'
            exit 1
        fi

        COMMITTER_TOKEN="$(echo -e "${GITHUB_TOKEN}" | tr -d '[:space:]')"

        git remote set-url origin https://x-access-token:$COMMITTER_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git fetch origin master develop
        git checkout develop
        git merge origin/master
        git push origin develop
